DROP DATABASE IF EXISTS burger;

CREATE DATABASE burger;

USE burger;

CREATE TABLE burgers (
	id INT NOT NULL AUTO_INCREMENT,
	burger_name VARCHAR(50) NOT NULL,
    devoured BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY (id)
);